name: satflow
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=0.13.0=pyhd8ed1ab_0
  - affine=2.3.0=py_0
  - aiohttp=3.7.4.post0=py39h3811e60_0
  - alembic=1.6.5=pyhd8ed1ab_0
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=2.110=mkl
  - blas-devel=3.9.0=10_mkl
  - blinker=1.4=py_1
  - bokeh=2.3.3=py39hf3d152e_0
  - boost-cpp=1.74.0=hc6e9bd1_3
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.2=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - cartopy=0.19.0.post1=py39h3b23250_0
  - certifi=2021.5.30=py39hf3d152e_0
  - cf-units=3.0.1.post0=py39hce5d2b2_0
  - cffi=1.14.6=py39he32792d_0
  - cfitsio=3.470=hb418390_7
  - cftime=1.5.0=py39hce5d2b2_0
  - chardet=4.0.0=py39hf3d152e_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cliff=3.8.0=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=2.1.2=py39hf3d152e_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=5.0.1=py39hf3d152e_0
  - configobj=5.0.6=py_0
  - cryptography=3.4.7=py39hbca0aa6_0
  - cudatoolkit=11.1.1=h6406543_8
  - curl=7.78.0=hea6ffbf_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py39h3811e60_3
  - dask=2021.7.2=pyhd8ed1ab_0
  - dask-core=2021.7.2=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_1
  - dbus=1.13.6=h48d8840_2
  - distributed=2021.7.2=py39hf3d152e_0
  - docutils=0.17.1=py39hf3d152e_0
  - donfig=0.6.0=pyhd8ed1ab_0
  - eccodes=2.21.0=ha0e6eb6_0
  - expat=2.4.1=h9c3ff4c_0
  - fasteners=0.16=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - fsspec=2021.7.0=pyhd8ed1ab_0
  - future=0.18.2=py39hf3d152e_3
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=h2b14fbe_4
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - google-auth=1.34.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.1=py_2
  - greenlet=1.1.0=py39he80948d_0
  - grpcio=1.38.1=py39hff7568b_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - h5py=3.3.0=nompi_py39h98ba4bc_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.6.3=py39hf3d152e_0
  - iris=3.0.4=py39hf3d152e_0
  - jasper=1.900.1=h07fcdf6_1006
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - kealib=1.4.14=hcc255d8_2
  - kiwisolver=1.3.1=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libaec=1.0.5=h9c3ff4c_0
  - libblas=3.9.0=10_mkl
  - libcblas=3.9.0=10_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.78.0=h2574ce0_0
  - libdap4=3.20.6=hd7c4107_2
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgdal=3.2.1=h38ff51b_7
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libglib=2.68.3=h3e27bee_0
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=10_mkl
  - liblapacke=3.9.0=10_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.17.2=h780b84a_1
  - librttopo=1.1.0=h1185371_6
  - libspatialite=5.0.1=he52d314_3
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libtiff=4.2.0=hbd63e13_2
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.42.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - mako=1.1.4=pyh44b312d_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h3811e60_0
  - matplotlib=3.4.2=py39hf3d152e_0
  - matplotlib-base=3.4.2=py39h2fa2bec_0
  - mkl=2021.3.0=h726a3e6_557
  - mkl-devel=2021.3.0=ha770c72_558
  - mkl-include=2021.3.0=h726a3e6_557
  - monotonic=1.5=py_0
  - msgpack-python=1.0.2=py39h1a9c180_1
  - multidict=5.1.0=py39h3811e60_1
  - mysql-common=8.0.25=ha770c72_0
  - mysql-libs=8.0.25=h935591d_0
  - ncurses=6.2=h58526e2_4
  - netcdf4=1.5.6=nompi_py39h36800e2_102
  - ninja=1.10.2=h4bd325d_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.67=hb5efdd6_0
  - numcodecs=0.8.0=py39he80948d_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.1=py39hde0f152_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pbr=5.6.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.2.0=py39hf95b381_1
  - pip=21.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - poppler=0.89.0=h2de54a5_5
  - poppler-data=0.4.10=0
  - postgresql=13.3=h2510834_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - proj=7.2.0=h277dcde_2
  - protobuf=3.17.2=py39he80948d_0
  - psutil=5.8.0=py39h3811e60_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydeprecate=0.3.1=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pykdtree=1.3.4=py39hce5d2b2_0
  - pyke=1.1.1=pyhd8ed1ab_1004
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyorbital=1.6.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyproj=3.1.0=py39h50a64a9_3
  - pyqt=5.12.3=py39hf3d152e_7
  - pyqt-impl=5.12.3=py39h0fcd23e_7
  - pyqt5-sip=4.19.18=py39he80948d_7
  - pyqtchart=5.12=py39h0fcd23e_7
  - pyqtwebengine=5.12.1=py39h0fcd23e_7
  - pyresample=1.20.0=py39hde0f152_0
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py39hf3d152e_3
  - pyspectral=0.10.5=pyhd8ed1ab_0
  - python=3.9.6=h49503c6_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-geotiepoints=1.2.1=py39hce5d2b2_1
  - python-xxhash=2.0.2=py39h3811e60_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=py3.9_cuda11.1_cudnn8.0.5_0
  - pytorch-lightning=1.4.1=pyhd8ed1ab_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h3811e60_0
  - qt=5.12.9=hda022c4_4
  - rasterio=1.2.6=py39h63973eb_0
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - satpy=0.29.0=pyhd8ed1ab_0
  - scipy=1.7.0=py39hee8e79c_1
  - setuptools=49.6.0=py39hf3d152e_3
  - shapely=1.7.1=py39ha61afbd_5
  - six=1.16.0=pyh6c4a22f_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlalchemy=1.4.22=py39h3811e60_0
  - sqlite=3.36.0=h9cd32fc_0
  - stevedore=3.3.0=py39hf3d152e_1
  - tbb=2021.3.0=h4bd325d_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tiledb=2.2.9=h91fcb0e_0
  - tk=8.6.10=h21135ba_1
  - toolz=0.11.1=py_0
  - torchmetrics=0.4.1=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_1
  - tqdm=4.62.0=pyhd8ed1ab_0
  - trollimage=1.15.1=pyhd8ed1ab_0
  - trollsift=0.3.5=pyh44b312d_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzcode=2021a=h7f98852_2
  - tzdata=2021a=he74cb21_1
  - udunits2=2.2.27.27=h975c496_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xarray=0.19.0=pyhd8ed1ab_1
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py39h3811e60_2
  - zarr=2.8.3=pyhd8ed1ab_0
  - zict=2.0.0=py_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
      - albumentations==1.0.3
      - antialiased-cnns==0.3
      - antlr4-python3-runtime==4.8
      - axial-attention==0.5.0
      - braceexpand==0.1.7
      - bravado==11.0.3
      - bravado-core==5.17.0
      - commonmark==0.9.1
      - einops==0.3.0
      - gitdb==4.0.7
      - gitpython==3.1.18
      - hydra-core==1.1.0
      - hydra-optuna-sweeper==1.1.0
      - imageio==2.9.0
      - iniconfig==1.1.1
      - joblib==1.0.1
      - jsonpointer==2.1
      - jsonref==0.2
      - jsonschema==3.2.0
      - lightning-bolts==0.3.4
      - neptune-client==0.10.2
      - neptune-pytorch-lightning==0.9.7
      - networkx==2.6.2
      - numpy==1.19.5
      - omegaconf==2.1.0
      - opencv-python-headless==4.5.3.56
      - optuna==2.4.0
      - perceiver-pytorch==0.5.1
      - pluggy==0.13.1
      - py==1.10.0
      - pygments==2.9.0
      - pyrsistent==0.18.0
      - pytest==6.2.4
      - python-dotenv==0.19.0
      - pytorch-msssim==0.2.1
      - pywavelets==1.1.1
      - rfc3987==1.3.8
      - rich==10.6.0
      - scikit-image==0.18.2
      - simplejson==3.17.3
      - smmap==4.0.0
      - strict-rfc3339==0.7
      - swagger-spec-validator==2.7.3
      - tifffile==2021.7.30
      - toml==0.10.2
      - torchvision==0.10.0
      - webcolors==1.11.1
      - webdataset==0.1.72
      - websocket-client==1.1.0
