name: satflow
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - affine=2.3.0=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - attrs=21.2.0=pyhd8ed1ab_0
  - bokeh=2.3.2=py39hf3d152e_0
  - boost-cpp=1.74.0=hc6e9bd1_3
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - cartopy=0.19.0.post1=py39h3b23250_0
  - certifi=2021.5.30=py39hf3d152e_0
  - cffi=1.14.5=py39he32792d_0
  - cfitsio=3.470=hb418390_7
  - cftime=1.5.0=py39hce5d2b2_0
  - chardet=4.0.0=py39hf3d152e_1
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - configobj=5.0.6=py_0
  - cryptography=3.4.7=py39hbca0aa6_0
  - cudatoolkit=11.1.1=h6406543_8
  - curl=7.77.0=hea6ffbf_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py39h3811e60_3
  - dask=2021.6.0=pyhd8ed1ab_0
  - dask-core=2021.6.0=pyhd8ed1ab_0
  - distributed=2021.6.0=py39hf3d152e_0
  - docutils=0.17.1=py39hf3d152e_0
  - donfig=0.6.0=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - fasteners=0.16=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - fsspec=2021.6.0=pyhd8ed1ab_0
  - future=0.18.2=py39hf3d152e_3
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=h2b14fbe_4
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - h5py=3.2.1=nompi_py39h98ba4bc_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - kealib=1.4.14=hcc255d8_2
  - kiwisolver=1.3.1=py39h1a9c180_1
  - krb5=1.19.1=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libcurl=7.77.0=h2574ce0_0
  - libdap4=3.20.6=hd7c4107_2
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgdal=3.2.1=h38ff51b_7
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.3=h3e27bee_0
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1013
  - liblapack=3.9.0=8_mkl
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.43.0=h812cca2_0
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.15.8=h780b84a_0
  - librttopo=1.1.0=h1185371_6
  - libspatialite=5.0.1=he52d314_3
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.2.0=hbd63e13_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h72842e0_0
  - llvm-openmp=11.1.0=h4bd325d_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=2.0.1=py39h3811e60_0
  - matplotlib-base=3.4.2=py39h2fa2bec_0
  - mkl=2020.4=h726a3e6_304
  - monotonic=1.5=py_0
  - msgpack-python=1.0.2=py39h1a9c180_1
  - ncurses=6.2=h58526e2_4
  - netcdf4=1.5.6=nompi_py39h36800e2_102
  - ninja=1.10.2=h4bd325d_0
  - numcodecs=0.7.3=py39he80948d_0
  - numpy=1.20.3=py39hdbf815f_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py39hde0f152_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.44=he1b5a44_0
  - pillow=8.2.0=py39hf95b381_1
  - pip=21.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - poppler=0.89.0=h2de54a5_5
  - poppler-data=0.4.10=0
  - postgresql=13.3=h2510834_0
  - proj=7.2.0=h277dcde_2
  - psutil=5.8.0=py39h3811e60_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pykdtree=1.3.4=py39hce5d2b2_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyorbital=1.6.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.0.1=py39h50a64a9_0
  - pyresample=1.20.0=py39hde0f152_0
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py39hf3d152e_3
  - pyspectral=0.10.5=pyhd8ed1ab_0
  - python=3.9.4=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-geotiepoints=1.2.1=py39hce5d2b2_1
  - python_abi=3.9=1_cp39
  - pytorch=1.8.0=cpu_py39h0fbb4fb_1
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h3811e60_0
  - rasterio=1.2.4=py39h63973eb_3
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - satpy=0.29.0=pyhd8ed1ab_0
  - scipy=1.6.3=py39hee8e79c_0
  - setuptools=49.6.0=py39hf3d152e_3
  - shapely=1.7.1=py39ha61afbd_5
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h7f98852_1
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.35.5=h74cdb3f_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tiledb=2.2.9=h91fcb0e_0
  - tk=8.6.10=h21135ba_1
  - toolz=0.11.1=py_0
  - torchvision=0.9.0=py39h93e5132_0_cpu
  - tornado=6.1=py39h3811e60_1
  - tqdm=4.61.0=pyhd8ed1ab_0
  - trollimage=1.15.0=pyhd8ed1ab_0
  - trollsift=0.3.5=pyh44b312d_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzcode=2021a=h7f98852_1
  - tzdata=2021a=he74cb21_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xarray=0.18.2=pyhd8ed1ab_0
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zarr=2.8.3=pyhd8ed1ab_0
  - zict=2.0.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
