# @package _group_
_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 0
max_epochs: 99999
min_steps: 20000
max_steps: 200000
val_check_interval: 1000
limit_train_batches: 2000
limit_val_batches: 500

weights_summary: null
progress_bar_refresh_rate: 10
# resume_from_checkpoint: null
