# @package _group_
_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 9999
min_steps: 0
max_steps: 999999999
limit_train_batches: 2000
limit_val_batches: 2000
limit_test_batches: 10000

terminate_on_nan: True
auto_lr_find: False
auto_scale_batch_size: False
accumulate_grad_batches: 1
precision: 16
# stochastic_weight_avg: True
fast_dev_run: False

reload_dataloaders_every_epoch: True

weights_summary: null
progress_bar_refresh_rate: 1
# resume_from_checkpoint: "/home/jacob/Development/satflow/satflow/logs/runs/2021-08-09/09-13-09/checkpoints/epoch=09.ckpt"
