# @package _group_
_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 0
max_epochs: 99999
limit_train_batches: 2000
limit_val_batches: 2000

terminate_on_nan: True
auto_lr_find: True
auto_scale_batch_size: False
reload_dataloaders_every_epoch: True

terminate_on_nan: True
auto_lr_find: False
auto_scale_batch_size: False
accumulate_grad_batches: 1
precision: 32
# stochastic_weight_avg: True

weights_summary: null
progress_bar_refresh_rate: 10
# resume_from_checkpoint: null
