_target_: satflow.models.join_model.JointPerceiver
input_channels: 23
sat_channels: 12
nwp_channels: 10
forecast_steps: 12
lr: 0.0005
input_size: 64
max_frequency: 32.0
depth: 6
num_latents: 256
cross_heads: 1
latent_heads: 8
cross_dim_heads: 8
latent_dim: 256
weight_tie_layers: False
decoder_ff: True
dim: 32
logits_dim: null
queries_dim: 32
latent_dim_heads: 64
visualize: False
use_learnable_query: True
predict_timesteps_together: True
nwp_modality: True
topographic_modality: True
sat_modality: True
hrv_sat_modality: True
