_target_: satflow.models.perceiver.Perceiver
input_channels: 16
sat_channels: 12
forecast_steps: 24
lr: 0.005
input_size: 32
max_frequency: 16.0
depth: 6
num_latents: 256
cross_heads: 1
latent_heads: 8
cross_dim_heads: 8
latent_dim: 256
weight_tie_layers: False
self_per_cross_attention: 2
dim: 32
logits_dim: null
queries_dim: 32
latent_dim_heads: 64
visualize: True
preprocessor_type: "metnet"
