# @package _group_
_target_: satflow.data.datamodules.SatFlowDataModule

batch_size: 1
data_dir: ${data_dir} # data_dir is specified in config.yaml
shuffle: 0
sources:
  train: "satflow-train-{00000..00214}.tar"
  val: "satflow-val-{00000..00060}.tar"
  test: "satflow-test-{00000..00057}.tar"
num_workers: 12
pin_memory: True
config:
  visualize: False
  num_timesteps: 6
  skip_timesteps: 3
  forecast_times: 24
  output_shape: 64
  output_target: 16
  target_type: "cloudmask"
  num_crops: 10
  use_topo: True
  use_latlon: True
  use_time: False
  time_aux: False
  use_mask: True
  use_image: False
  add_pixel_coords: False
  time_as_channels: False
  bands:
    [
      "HRV",
      "IR016",
      "IR039",
      "IR087",
      "IR097",
      "IR108",
      "IR120",
      "IR134",
      "VIS006",
      "VIS008",
      "WV062",
      "WV073",
    ]
  transforms: {}
