general:
  description: Config for producing batches on OCF's on-premises hardware.
  name: on_premises
input_data:
  default_forecast_minutes: 120
  default_history_minutes: 30
  #---------------------- GSP -------------------
  gsp:
    gsp_zarr_path: /mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/PV/GSP/v3/pv_gsp.zarr

  #---------------------- NWP -------------------
  nwp:
    nwp_channels:
      - t
      - dswrf
      - prate
      - r
      - sde
      - si10
      - vis
      - lcc
      - mcc
      - hcc
    nwp_image_size_pixels: 64
    nwp_zarr_path: /mnt/storage_ssd_8tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/NWP/UK_Met_Office/UKV/zarr/UKV_intermediate_version_2.zarr
    history_minutes: 60

  #---------------------- PV -------------------
  pv:
    pv_filename: /mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/PV/Passiv/ocf_formatted/v0/passiv.netcdf
    pv_metadata_filename: /mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/PV/Passiv/ocf_formatted/v0/system_metadata_OCF_ONLY.csv
    get_center: false

  #---------------------- Satellite -------------
  satellite:
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels: 24
    satellite_zarr_path: /mnt/storage_ssd_8tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/zarr/v2/eumetsat_zarr_*

  hrvsatellite:
    hrvsatellite_channels:
      - HRV
    hrvsatellite_image_size_pixels: 64
    hrvsatellite_zarr_path: /mnt/storage_ssd_8tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/zarr/v2/hrv_eumetsat_zarr_*

  # ------------------------- Sun ------------------------
  sun:
    sun_zarr_path: /mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/Sun/v1/sun.zarr

  # ------------------------- Topographic ----------------
  topographic:
    topographic_filename: /mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/Topographic/europe_dem_1km_osgb.tif

output_data:
  filepath: /mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v14
process:
  batch_size: 32
  seed: 1234
  upload_every_n_batches: 0 # Write directly to output_data.filepath, not to a temp directory.
